### ISSUE TITLE
训练出来的权重大小和参数量？

### ISSUE THREAD

**Issue by Ringhu** [liux0614/yolo_nano#11]
我看论文里的网络结构还是比较复杂的，对这个网络最终产生的权重文件是否真的只有4MB有些怀疑，想问您复现代码最终训练得到的权重文件大小是多少呢？

**Comment by liux0614** [comment]
我没有把权重单独保存，模型权重+optimizer权重 35MB

**Comment by Ringhu** [comment]
谢谢回复，那请教一下既然这个网络的权重并没有论文里描述的那么小，这个网络的意义在哪里呢，提高了mAP?

**Comment by liux0614** [comment]
我也觉得很奇怪 为什么我训练出来的模型比他们说的大。 因为他们没有提供细节，不知道是不是用了半精度浮点， 是不是用了model compression的一些技术压缩了模型。

**Comment by DocF** [comment]
复现大佬没仔细看论文，作者论文中说了一嘴用了int8，模型参数3M多点，用int8保存模型权重文件不到4M。

**Comment by liux0614** [comment]
> 复现大佬没仔细看论文，作者论文中说了一嘴用了int8，模型参数3M多点，用int8保存模型权重文件不到4M。

对不起 我的确没看到这句话 我回去找了一下 是在2.2 Machine-driven design exploration提到的吧？

> iii) 8-bit weight precision.

**Comment by DocF** [comment]
对的，至于精度这就不好说了，毕竟作者也没开源代码，anyway还是要膜拜一下复现大佬 orz

**Comment by Ringhu** [comment]
@liux0614 
mAP的问题可能是因为你用的是COCO数据集？我之前用COCO数据集训练tiny-yolo的mAP的确比在VOC2007上的mAP小很多。

**Comment by liux0614** [comment]
> @liux0614
> mAP的问题可能是因为你用的是COCO数据集？我之前用COCO数据集训练tiny-yolo的mAP的确比在VOC2007上的mAP小很多。

可能是的，但是最近忙着别的 没时间在VOC上面测试:(

**Comment by Ringhu** [comment]
@DocF BTW我感觉这个论文拿用FP32存储的tiny-yolov3和用int8存储的yolo-nano来对比有点不地道。。
![20191122104429](https://user-images.githubusercontent.com/47172283/69393870-559c4380-0d15-11ea-9b03-e5500c8264d7.png)

**Comment by DocF** [comment]
@Ringhu 是的，作者很鸡贼，不比模型参数比模型大小
