### ISSUE TITLE
论文复现问题

### ISSUE THREAD

**Issue by whuhit** [liux0614/yolo_nano#13]
请问下代码basic_layers.py中的PEP模块和EP模块的实现与论文中的结构图并不相同，少了一层expansion layer和projection layer，这里是基于什么考虑的呢？

**Comment by liux0614** [comment]
没有吧 我的理解是论文中的EP整个结构就是separable convolution

**Comment by whuhit** [comment]
> 没有吧 我的理解是论文中的EP整个结构就是separable convolution

哦哦，看到了，都在sepconv里，谢谢
