### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by dongzhen123** [liux0614/yolo_nano#2]
1.One line of code is missing in yolo_nano.py,that is "out = self.pep4(out)".
2.Do any training use this code?and the test accuary compare with the paper?

**Comment by liux0614** [comment]
1.Thank you for your reminder.
2.I haven't tested accuracy, but I plan to compare the performance this week

**Comment by johnjunjun7** [comment]
> 1.Thank you for your reminder.
> 2.I haven't tested accuracy, but I plan to compare the performance this week

Want to use your code for training, and find that the coco data format you read is not a standard data format. Do you have the source code for data processing ?

**Comment by liux0614** [comment]
As I wrote this implementation for my own project at first, I didn't consider the COCO dataset. But I'm going to support COCO dataset. I think I can finish the corresponding code today or tommorrow.
