### ISSUE TITLE
预训练模型的问题

### ISSUE THREAD

**Issue by Zmjcc** [liux0614/yolo_nano#4]
请问您在训练时如何解决没有预训练模型的问题？我用darknet框架训练时在没有预模型的情况下训练voc数据集loss并不会收敛。

**Comment by tonyyang1995** [comment]
I think you can start with a small dataset first. It is a good way to debug for your code.

**Comment by zhqx511** [comment]
不是有个.74文件吗，用那个就好了，如果用这个还不能收敛，就要检查一下数据集和训练代码了。
