### ISSUE TITLE
大佬想问一下您的代码细节问题

### ISSUE THREAD

**Issue by gongpx20069** [liux0614/yolo_nano#5]
您的YOLOLayer类里的forward函数里的targets的大小是什么呢？能给个比较详细的解释吗？我想用VOC数据集来训练，也是第一次接触YOLO，拜托了

**Comment by liux0614** [comment]
targets 包括: idx, class_id, x, y, h, w (yolo format)
idx用于把bounding boxes和image对应起来，是个最小为0，最大为batch size大小的整数

**Comment by gongpx20069** [comment]
也就是说，这里的class_id, x, y, h, w都是int
您比如说batchsize=1，这个时候，targets的size就是(1,1,4)吗？

**Comment by liux0614** [comment]
不是 只有idx 和 class_id 是 int （但是在实际计算里的时候是这两个整数会被转化成float的，e.g. 1 -> 1.0)
targets的size应该是2d的: batch size x 6

**Comment by gongpx20069** [comment]
大佬，假如说是(batch_size, 6)的大小的话，假如一张图的bbox有多个呢？这不就没办法表示了吗？

**Comment by liux0614** [comment]
不好意思 我说错了 target size应该是 一个batch里面bounding box总数 x 6
然后idx用来标识每个bounding box该属于哪张图片, class_id标识这个bounding box属于哪类, x y h w是yolo格式的坐标

**Comment by gongpx20069** [comment]
大佬，我代码看得有点晕，这个idx是指该图片矩阵在batch中的位置吧？比如第一张的话idx=0；第二张idx=1这样？

**Comment by liux0614** [comment]
对的
比如你有三张图片，第一张图片有3个bbox，第二张有4个，第三张有5个，
那么你的targets就会有12个，前三个bbox的idx为0（对应第一张图片），之后的四个bbox的idx为1（对应第二张图片，最后5个bbox的idx为2（对应第三张图片

**Comment by gongpx20069** [comment]
大佬，我再问一下，这里的x,y,w,h都是[0-1]之间的数字吧

**Comment by gongpx20069** [comment]
大佬，我还是问清楚一点，比如我第一张图片的第一个bbox（属于第二类）的数据，则我的target是六个维度[0, 1, x, y, w, h]，其中x, y, w, h都是处于[0,1]之间的浮点数。最后网络yololayer的输出结果，是真实图像的一个坐标[x , y, w, h, bbox置信度, class1置信度, class2置信度,...]。
训练后我取了最大bbox置信度最大的数据，现在我的输出里，class1和class2的置信度都是1。。。。。

**Comment by gongpx20069** [comment]
稳了大佬，我大概都看懂了

**Comment by liux0614** [comment]
优秀
