### ISSUE TITLE
网络设计几点疑问

### ISSUE THREAD

**Issue by mozpp** [liux0614/yolo_nano#6]
看了代码，和yolo nano论文，有几点疑问：
1，yolo最后一层应该是纯卷积吧？实现中好像是 卷积+bn+激活。
例如 `       out_conv10 = self.conv10(out)`
2，论文中EP模块是有elementwise相加的，但是实现中发现channel不同，实际EP没有elementwise相加，是论文那边表述错了吗？

**Comment by liux0614** [comment]
1.你是对的 最后一层不该加bn，我写的时候忘记去掉最后的bn了，不好意思。
2.这个问题我理解没有错误的话，你想说的是：是不是EP没有像residualblock一样，当input channles大于output channles时，将input channels 降至和 output channels一样，然后相加？
我目前写的EP和PEP在channel不同时 的确没有elementwise相加的操作，主要参考了mnasnet这类网络的SepConv_3x3（见https://github.com/AnjieZheng/MnasNet-PyTorch/blob/master/MnasNet.py），也有考虑少了一个downsampler能让最终模型小一点。如果最终效果不好，我会去尝试加入downsampler。
